# Generated by Django 3.0.5 on 2020-04-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название страны')),
                ('number', models.IntegerField(default=0, verbose_name='номер айди')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название лиги')),
                ('number', models.IntegerField(default=0, verbose_name='номер айди')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corners.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тимы')),
                ('number', models.IntegerField(default=1, verbose_name='айдишник')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corners.League')),
            ],
        ),
        migrations.CreateModel(
            name='StatsCorner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тимы')),
                ('home', models.BooleanField(verbose_name='домашний матч')),
                ('away', models.BooleanField(verbose_name='гостевой матч')),
                ('cup', models.BooleanField(verbose_name='кубок')),
                ('league', models.BooleanField(verbose_name='домашняя лига')),
                ('first_half', models.BooleanField(verbose_name='первая половина матча')),
                ('second_half', models.BooleanField(verbose_name='вторая половина матча')),
                ('individual_total', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='ИНДИВИДУАЛЬНЫЙ ТОТАЛ')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corners.Team')),
            ],
        ),
    ]
